### ISSUE TITLE
remove starting `task` from a task name?

### ISSUE THREAD

**Issue by devoncarew** [google/grinder.dart#187]
When mapping from annotation method names to task names, we convert camel case to dashes (`fooBar` ==> `foo-bar`). Should we also remove any leading `task` (`taskFooBar` ==> `foo-bar`)? The reason for this it to make it easier to identify methods that are tasks in a source overview, like in the editor's outline view.

**Comment by seaneagan** [comment]
I think it'd be nice to have everyone using the same naming convention for their task methods, and if we support both with and without a `task` prefix, we would lose that.  And I like without `task` better since it's more readable, `task` would be redundant with `@Task`, and the methods could even be used as ordinary dart APIs (and not command-line tasks).

I think there may be other strategies to tell any non-task methods apart in an outline view, such as making them private, or putting them all at the end of the file.

**Comment by devoncarew** [comment]
Yeah, the pattern I'm using right now is:

- task method are annotated with `@Task` annotations
- they're public - all other supporting methods are private
- they're listed in approx the lifecycle order

Perhaps having more visibility of annotations in the outline view would help here.
