### ISSUE TITLE
Come up with a nice tagline for grinder

### ISSUE THREAD

**Issue by seaneagan** [google/grinder.dart#189]

**Comment by seaneagan** [comment]
@devoncarew @sethladd 

Before I do a new PR, what do you think about this:

# Grinder for Dart 
> Let it do your *darty* work.

**Comment by zoechi** [comment]
It's nice. For me it's important to immediately get and idea what a package does, otherwise I usually get more angry than curious. When I read into the readme and don't get an idea what the package is about very fast I have to be desperate to continue.

> Automate your darty workflow.
or the current
> All your darty work, automated.

are not as catchy but IMHO tell more what the package is about.

**Comment by seaneagan** [comment]
@zoechi thanks!  I agree the work "automate" is nice to include.  I really like the "*darty* work" pun as well.  What about this:

> Automates your *darty* work.

**Comment by zoechi** [comment]
I like it.

**Comment by devoncarew** [comment]
We currently have `A task based, dependency aware build system` in a few places. I'd be up for including 

    Automate your Dart workflow

or

    All your Dart work, automated

while keeping the longer description in some places (where more clarity is necessary). I think I want to avoid the _darty_ / _dirty_ pun, just because we have some pre-existing issues with the current name -

But I like the idea of adding a nice, short, motivational tagline.

**Comment by seaneagan** [comment]
If we keep the existing name, we ought to solidify a fun analogy/branding that folks can identify the project with, which also helps avoid any analogies we don't want.  That was the goal of this issue.  But since we are considering a rename, I can see waiting until we make a final decision on that.

IMO grinder is fundamentally a "task runner", "task framework", or "automation framework"... "for dart", as opposed to a "build system".  Agree?  Also, can we change "Grinder for Dart" to just "Grinder", and just reference "Dart" in the tagline?

How about one of these three:

# Grinder
> Dart workflows automated.
> Task runner for Dart.
> Task framework for Dart.

?

**Comment by devoncarew** [comment]
+1 to the first one - `Dart workflows automated.`. I would call it currently a task automation framework; I would love to see if it could be expanded into a full build system, as in, recognizing and not doing work that is not necessary.

**Comment by zoechi** [comment]
+1 `Dart workflows automated.`

I wasn't able to comprehend what 'tasks'  should be about before having a closer look at Grinder. I don't remember exactly what motivated me, I guess it was an example grind.dart file. I was never motivated to give HOP a try, because, I didn't understand what it's purpose is actually. Might just be me. If you know such a tool from other languages associated with task you might see this totally different. 'Workflow' isn't perfect but IMHO better. 

Framework is a very meaningless word to me, I would only  use to fill empty space ;-)
