### ISSUE TITLE
Integrate with the `test` test runner

### ISSUE THREAD

**Issue by devoncarew** [google/grinder.dart#58]
Integrate the Dart Test Runner (https://github.com/google/test_runner.dart) in some way.

**Comment by seaneagan** [comment]
Updating to reflect that `test_runner` is being replaced by `pub run unittest:unittest`.

Grinder already has conveniences to `pub global run` things, but not to `pub run` them, see #153, which is what I think we'd want to use here.  Ideally, we could just call a dart API instead of `pub run`, see https://github.com/dart-lang/unittest/issues/23.

This would also likely deprecating grinder's `Tests` class, or updating its API and impl to match the `unittest` test runner.

**Comment by devoncarew** [comment]
> This would also likely deprecate grinder's Tests class, or update its API and impl to match the unittest test runner.

Yeah, we'll want to follow whatever the emerging consensus is.

**Comment by devoncarew** [comment]
`test` (`0.12.0`) is out now. For an example of driving it from grinder (w/o a custom wrapper), see #221.
