### ISSUE TITLE
Annotation to define Tasks

### ISSUE THREAD

**Issue by seaneagan** [google/grinder.dart#79]
Something like this:

```dart

import 'package:grinder:grinder.dart';

const main = startGrinder;

@GrinderTask()
init() {
  // ...
}

@GrinderTask(deps: const ['init'])
test() {
  // ...
}

```

**Comment by seaneagan** [comment]
Would be nice if properties worked too:

```dart
@GrinderTask()
const init = Pub.get;
```

**Comment by devoncarew** [comment]
You and Seth both :) I thought he had filed an issue about using annotations but I can't find anything now.

I'd been pretty leery of them due to lots of negative experience with what they did to browser based apps - generally expand code greatly, and or complicate the development cycle. I'd been hesitant to use them in CLI apps; it that code leaks out your web app would have issues.

I have less concern about using them in a CLI app now though. When I have cycles, my plan for grinder is to re-evaluate it's API and design after taking a look at gulp. It's really taken off for JS work; I want to see if there are things we should borrow, or even if there are ways we could interoperate (like consuming gulp plugins). That would probably be a good time to re-evaluate the API, and batch up breaking changes together.

**Comment by seaneagan** [comment]
I think most of the things that would be implemented as streaming gulp plugins in JavaScript just end up as pub transformers in dart.  So piping one task to another is not *as* important for grinder.  One nice thing about the gulp API though is that it's easier to define the logic for a task inline:

```javascript
gulp.task('init', function () {
  // ...
});
gulp.task('build', ['init'], function () {
  // Long
  // code
  // block.
});
```

```dart
task('init', () {
  // ...
});
task('build', () {
  // Long
  // code
  // block.
}, ['init']);
```

`['init']` gets lost after the long code block.  This is partly dart's fault:

https://dartbug.com/22136
